name: "Bug Report"
description: "Report a bug"
title: "BUG | "
labels: ["type:bug", "status:backlog"]
body:
  - type: textarea
    id: bug_description
    attributes:
      label: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected_result
    attributes:
      label: Expected result
    validations:
      required: true
  - type: textarea
    id: actual_result
    attributes:
      label: Actual result
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - critical
        - high
        - medium
        - low
    validations:
      required: true
